import Header from '@/components/Header/Header';
import Head from 'next/head';
import Hero from '@/components/Hero/Hero';
import About from '@/components/About/About';
import WorkExperiance from '@/components/WorkExperiance/WorkExperiance';

export default function Home() {
	return (
		<>
			<div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0'>
				<Head>
					<title>Marias Portfolio</title>
					<meta name='description' content='Generated by create next app' />
					<meta name='viewport' content='width=device-width, initial-scale=1' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<Header />
				<section id='hero' className='snap-start'>
					<Hero />
				</section>
				<section id='about' className='snap-center'>
					<About />
				</section>
				{/* experiance  */}
				<section id='experiance' className='snap-center'>
					<WorkExperiance />
				</section>
				{/* skills  */}
				{/* projects  */}
				{/* contact  */}
				{/* footer  */}
			</div>
		</>
	);
}
