import Header from '@/components/Header/Header';
import Head from 'next/head';
import Hero from '@/components/Hero/Hero';

export default function Home() {
	return (
		<>
			<div className='bg-[rgb(36,36,36)] text-white h-screen'>
				<Head>
					<title>Marias Portfolio</title>
					<meta name='description' content='Generated by create next app' />
					<meta name='viewport' content='width=device-width, initial-scale=1' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				{/* header  */}
				<Header />
				{/* hero  */}
				<section id='hero'>
					<Hero />
				</section>
				{/* about  */}
				{/* experiance  */}
				{/* skills  */}
				{/* projects  */}
				{/* contact  */}
				{/* footer  */}
			</div>
		</>
	);
}
