import Header from '@/components/Header/Header';
import Head from 'next/head';
import Hero from '@/components/Hero/Hero';
import About from '@/components/About/About';
import WorkExperience from '@/components/WorkExperience/WorkExperience';
import Skills from '@/components/Skills/Skills';
import Projects from '@/components/Projects/Projects';

export default function Home() {
	return (
		<>
			<div className='bg-[#1C3334] text-white h-screen snap-y snap-mandatory overflow-scroll z-0'>
				<Head>
					<title>Marias Portfolio</title>
					<meta name='description' content='Generated by create next app' />
					<meta name='viewport' content='width=device-width, initial-scale=1' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<Header />
				<section id='hero' className='snap-start'>
					<Hero />
				</section>
				<section id='about' className='snap-center'>
					<About />
				</section>
				<section id='experience' className='snap-center'>
					<WorkExperience />
				</section>
				<section id='skills' className='snap-start'>
					<Skills />
				</section>
				{/* projects  */}
				<section id='projects' className='snap-start'></section>
				<Projects />
				{/* contact  */}
				{/* footer  */}
			</div>
		</>
	);
}
